### ISSUE TITLE
How do you generate NetFile.cs?

### ISSUE THREAD

**Issue by linwe2012** [SvenMertin/SUMO3d#1]
May I ask which tool did you use to generate NetFile.cs?
And where can I find the `.xsd` used to generate NetFile.cs? Are they those `xsd` files in the sumo repo? Does your tool combine them together?

**Comment by SvenMertin** [comment]
Hey there!
If I remember correctly, I used Xsd.exe which comes with visual studio (see [here](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/x6c1kb0s(v=vs.100)?redirectedfrom=MSDN)) to generate the c# classes.

The xsd files were just taken from the sumo repo ([here](https://github.com/eclipse/sumo/tree/master/data/xsd) or [here](https://sumo.dlr.de/xsd/))

Regards!

Edit:
I remeber that there were many dependencies between the xsd files, so I think you will need to include all files to be able to generates the classes.

**Comment by linwe2012** [comment]
Ohh, thank you so much! 👍
